#!/bin/bash
# -*- mode: sh; -*-

# pacbins: print the list of files installed under BINS (defaults to /usr/bin)
# belonging to a certain Pacman package.

BINS=${BINS:="/usr/bin"}

usage () {
    >&2 echo "Usage: $0 [PACKAGE]..."
    exit $EXIT_FAILURE
}

if [[ $# -eq 0 ]]; then
    usage
fi

while [[ $# -gt 0 ]];
do
    echo "$1:"

    pacman -Qq $1 > /dev/null 2>&1

    if [[ $? -gt 0 ]]; then
	echo "isn't a package managed by Pacman"
	shift && continue
    fi

    pacman -Qql $1 2> /dev/null | grep -E "$BINS/[a-zA-Z0-9]{1}"

    if [[ $? -gt 0 ]]; then
	echo "no files in $BINS"
    fi

    shift
done
