#!/bin/bash
# -*- mode: sh; fill-column: 80; -*-

# Give exit codes used here clear names.
EXIT_FAILURE=1

# If the first argument doesn't exclusively contain a number, remind the user
# how to correctly use this command and exit with failure code.
regex='^[0-9]+$'
if [[ ! $1 =~ $regex ]]; then
    echo "$(basename $0): PID"
    exit $EXIT_FAILURE
fi

PID="$1"

# If a PID is valid, a directory named after it will exist on the /proc file
# system. Here we verify that said directory exists and that there is a file
# with the process's starting command. Otherwise, explain the error to the user
# and fail.
if [[ -d /proc/${PID} && -f /proc/${PID}/cmdline ]]; then
    xargs --null -a /proc/${PID}/cmdline
else
    echo "There is no process with a PID of $PID."
    exit $EXIT_FAILURE
fi
