#!/bin/bash
# -*- mode: sh; tab-width: 4; -*-

# Find out on which system we are
hostname=$(uname -n)
username=$(whoami)

# Find the name of the network interface being used and its ip address
netif=$(route | grep '^default' | grep -o '[^ ]*$')
ipaddr=$(ip -f inet addr show $netif | awk '/inet / {print $2}' | \
			 cut -d '/' -f 1)

# Get the name of the user's default shell (from /etc/passwd)
usershell=$(awk -F: -v user=$username '$1 == user {print $NF}' /etc/passwd | \
				xargs basename)

# Get system performance and utilization information
loadavg=$(cat /proc/loadavg | cut -d " " -f 1-3)
usedmem=$(free -h | awk 'FNR == 2 {print $3}')
freemem=$(free -h | awk 'FNR == 2 {print $4}')
availmem=$(free -h | awk 'FNR == 2 {print $7}')

# greetingsFont is the figlet font. If not already set, default to font "script"
greetingsFont=${greetingsFont:=script}

# Verify that figlet is installed on system, and if it is not: fail
if ! [ -x "$(command -v figlet)" ]; then
	echo "This scripts, which greets the user, requires figlet to work."
	exit 1
else
	figlet -f "$greetingsFont" "$hostname" | sed '/^\s*$/d'
	echo
fi

# Print everything we've gathered so far in a clear way
echo "$(date) (user: $username, ip: $ipaddr, shell: $usershell)"
echo "load average: $loadavg, mem: used: $usedmem, free: $freemem, available: \
$availmem"
